mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from home import views
from reservations import views as reservationsviews

urlpatterns = [
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('transfer/', include('transfer.urls')),
    path('user/', include('user.urls')),
    path('reservations/', include('reservations.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/', views.category_transfer, name='category_transfer'),
    path('transfer/<int:id>/<slug:slug>/', views.transfer_detail, name='transfer_detail'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('reservcart/', reservationsviews.reservcart, name='sss'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.sss, name='sss'),

]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transfer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')

]

user/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('reservations/', views.reservations, name='reservations'),
    path('reservationdetails/<int:id>', views.reservationdetails, name='reservationdetails'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'YES'),
        ('False', 'NO'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=6)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=150)
    instagram = models.CharField(blank=True, max_length=150)
    twitter = models.CharField(blank=True, max_length=150)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactformMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(max_length=50, blank=False)
    message = models.CharField(blank=False, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model = ContactformMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'name-input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'name-input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'name-input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'name-input', 'placeholder': 'Your Message', 'row': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'YES'),
        ('False', 'NO'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

transfer/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=30)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' ->'.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Transfer(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    LOCATION = (
        ('Address', 'Address'),
        ('Hotel', 'Hotel'),
    )
    BAGGAGE = (
        ('YES', 'YES'),
        ('NO', 'NO')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(null=True, upload_to='images/', default='images/default.jpg')
    airport = models.CharField(max_length=50)
    seat = models.IntegerField()
    shuttle = models.CharField(max_length=50)
    price = models.FloatField()
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=30, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    transfer = models.ForeignKey(Transfer, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    transfer = models.ForeignKey(Transfer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.TextField(max_length=200, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']

home/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.form import SignUpForm
from home.models import Setting, ContactformMessage, ContactForm, UserProfile, FAQ
from transfer.models import Category, Transfer, Images, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    daytransfer = Transfer.objects.all()[:4]
    lasttransfer = Transfer.objects.all().order_by('-id')[:4]
    context = {'setting': setting, 'category': category, 'daytransfer': daytransfer, 'lasttransfer': lasttransfer, }
    return render(request, 'index.html', context)


def aboutus(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting,
               'category': category, }
    return render(request, 'aboutus.html', context)


def references(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting,
               'category': category, }
    return render(request, 'references.html', context)


def contact(request):
    if request.method == 'POST':  # form post edildiyse
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactformMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Your Message sent successfully.")
            return HttpResponseRedirect('/contact')
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    form = ContactForm()
    context = {'setting': setting, 'form': form,
               'category': category, }
    return render(request, 'contact.html', context)


def category_transfer(request, id, slug):
    categorydata = Category.objects.get(pk=id)
    category = Category.objects.all()
    transfer = Transfer.objects.filter(category_id=id, status='True')
    context = {'transfer': transfer,
               'category': category,
               'categorydata': categorydata}
    return render(request, 'transfer.html', context)


def transfer_detail(request, id, slug):
    current_user = request.user
    category = Category.objects.all()
    profile = UserProfile.objects.get(user_id=current_user.id)
    images = Images.objects.filter(transfer_id=id)
    transfer = Transfer.objects.get(pk=id)
    comments = Comment.objects.filter(transfer_id=id, status='True')
    context = {'category': category, 'transfer': transfer, 'images': images, 'comments': comments, 'profile': profile}
    return render(request, 'transfer_detail.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Invalid Login ")
            return HttpResponseRedirect('/login')
    category = Category.objects.all()
    context = {'category': category,
               }
    return render(request, 'login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.jpg"
            data.save()
            messages.success(request, 'Welcome.... Your Profile was successfully registered')
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }
    return render(request, 'signup.html', context)


def sss(request):
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('ordernumber')
    context = {
        'category': category,
        'faq': faq
    }
    return render(request, 'faq_page.html', context)

transfer/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from transfer.models import CommentForm, Comment


def index(request):
    return HttpResponse("Transfer page")


@login_required(login_url='/login')
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            data = Comment()
            data.user_id = current_user.id
            data.transfer_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "YOUR COMMENT WAS SENT SUCCESSFULLY..")
            return HttpResponseRedirect(url)
    messages.warning(request, "YOUR COMMENT DID NOT SAVA... PLEASE CHECK OUT")
    return HttpResponseRedirect(url)

home/templates/aboutus.html
{% extends "homebase.html" %}

{% block title %} Aboutus-{{ setting.company }}{% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}
{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block body %}
<section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>About US</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
<!--== About Page Content Start ==-->
    <section id="about-area" class="section-padding">
        <div class="container">
            <div class="row">
                {{ setting.aboutus|safe }}
            </div>

            <div class="row">

            </div>

        </div>
    </section>
    <!--== About Page Content End ==-->
{% endblock %}

home/templates/contact.html
{% extends "homebase.html" %}

{% block title %} Contact-{{ setting.company }}{% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}
{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block body %}
<section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Contact Us</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
<!--== About Page Content Start ==-->
<div class="contact-page-wrao section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="section-title  text-center">
                        <h2>Contact Form</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                          <div class="alert alert-{{message.tags}}" role="alert">
                               {{ message }}
                           </div>
                    {% endfor %}
                {% endif %}
                    <div class="contact-form">
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form.as_p }}
                        <div class="input-submit">
                                <button type="submit">Submit Message</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="section-title  text-center">
                        <h2>Contact Information</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>
                    {{ setting.contact|safe }}
                </div>
            </div>
        </div>
</div>
<!--== Map Area Start ==-->
    <div class="maparea">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29213.038296132225!2d90.39150904197642!3d23.760577791538438!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c783c3404f0d%3A0x76ae0d2edabc81df!2sHatir+Jheel!5e0!3m2!1sen!2sbd!4v1517941663187"></iframe>
    </div>
    <!--== Map Area End ==-->
{% endblock %}

home/templates/index.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }}{% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}
{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block body %}
    {% include "content.html" %}
{% endblock %}

home/templates/sidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/transfer_detail.html
{% extends "homebase.html" %}

{% block title %} {{ transfer.title }}{% endblock %}
{% block keywords %} {{ transfer.keywords }} {% endblock %}
{% block description %} {{ transfer.description}} {% endblock %}
{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block body %}
<section id="page-title-area" class="section-padding overlay">
    <div class="container">
        <div class="row">
            <!-- Page Title Start -->
            <div class="col-lg-12">
                <div class="section-title  text-center">
                    <h2>Car Details</h2>
                    <span class="title-line"><i class="fa fa-car"></i></span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
            <!-- Page Title End -->
        </div>
    </div>
</section>
<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
    <div class="container">
        <div class="row">
            <!-- Car List Content Start -->
            <div class="col-lg-8">
                <div class="car-details-content">
                    <h2>{{ transfer.title }}<span class="price">Rent: <b>{{ transfer.price }}</b></span></h2>
                    <div class="car-preview-crousel">
                        <div class="single-car-preview">
                            <img src="{{ transfer.image.url }}" alt="JSOFT">
                        </div>
                        {% for rs in images %}
                        <div class="single-car-preview">
                            <img src="{{ rs.image.url }}" alt="JSOFT">
                        </div>
                        {% endfor %}
                    </div>
                    <div class="car-details-info">
                        <h4>Additional Info</h4>
                        <p>{{ transfer.detail | safe}}</p>
                        {%if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <div class="review-area">
                            <h3>Write Your Comment And Review</h3>
                            <div class="review-area">
                                <div class="review-form">
                                    <form action="/transfer/addcomment/{{ transfer.id }}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="name-input">
                                                    <input type="text" name="subject" placeholder="subject" id="id_subject">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="message-input">
                                            <textarea name="comment" id="id_comment" cols="30" rows="5" placeholder="Write Your Feedback Here!"></textarea>
                                        </div>
                                        {% if user.id is not none %}
                                        <div class="input-submit">
                                            <button type="submit">Submit</button>
                                            <button type="reset">Clear</button>
                                        </div>
                                        {% else %}
                                        Please <a href="/login">  Login </a>To Adding Comment
                                        {%  endif %}
                                    </form>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="single-sidebar">
                        <h3>Comments</h3>

                        <div class="sidebar-body">
                            <ul class="recent-tips">
                                {% for rs in comments %}
                                <li class="single-recent-tips">
                                    <div class="recent-tip-thum">
                                        <a href="#"><img src="{{ profile.image.url }}" alt="JSOFT" style="border-radius: 50%;width:40px"></a>
                                    </div>
                                    <div class="recent-tip-body">
                                        <h5>{{ rs.subject }}</h5>
                                        <h4><a href="#">{{ rs.comment }}</a></h4>
                                        <span class="date">{{ rs.create_at}}</span> {{rs.user.first_name}}
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            <!-- Car List Content End -->

            <!-- Sidebar Area Start -->
            <div class="col-lg-4">
                <div class="sidebar-content-wrap m-t-50">
                    <!-- Single Sidebar Start -->
                    <div class="single-sidebar">
                        <h3>For More Informations</h3>
                        <form action="/reservations/addtoreserv/{{ transfer.id }}/{{ transfer.slug }}" method="post">
                            {% csrf_token %}
                        <div class="sidebar-body">
                            <button type="submit">Reserv it</button>
                        </div>
                            </form>
                    </div>
                    <!-- Single Sidebar End -->

                    <!-- Single Sidebar Start -->
                    <div class="single-sidebar">
                        <h3>Rental Tips</h3>

                        <div class="sidebar-body">
                            <ul class="recent-tips">
                                <li class="single-recent-tips">
                                    <div class="recent-tip-thum">
                                        <a href="#"><img src="assets/img/we-do/service1-img.png" alt="JSOFT"></a>
                                    </div>
                                    <div class="recent-tip-body">
                                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                                        <span class="date">February 5, 2018</span>
                                    </div>
                                </li>

                                <li class="single-recent-tips">
                                    <div class="recent-tip-thum">
                                        <a href="#"><img src="assets/img/we-do/service3-img.png" alt="JSOFT"></a>
                                    </div>
                                    <div class="recent-tip-body">
                                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                                        <span class="date">February 5, 2018</span>
                                    </div>
                                </li>

                                <li class="single-recent-tips">
                                    <div class="recent-tip-thum">
                                        <a href="#"><img src="assets/img/we-do/service2-img.png" alt="JSOFT"></a>
                                    </div>
                                    <div class="recent-tip-body">
                                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                                        <span class="date">February 5, 2018</span>
                                    </div>
                                </li>

                                <li class="single-recent-tips">
                                    <div class="recent-tip-thum">
                                        <a href="#"><img src="assets/img/we-do/service3-img.png" alt="JSOFT"></a>
                                    </div>
                                    <div class="recent-tip-body">
                                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                                        <span class="date">February 5, 2018</span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Sidebar End -->

                    <!-- Single Sidebar Start -->
                    <div class="single-sidebar">
                        <h3>Connect with Us</h3>

                        <div class="sidebar-body">
                            <div class="social-icons text-center">
                                <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                                <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                                <a href="#" target="_blank"><i class="fa fa-behance"></i></a>
                                <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                                <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
                            </div>
                        </div>
                    </div>
                    <!-- Single Sidebar End -->
                </div>
            </div>
            <!-- Sidebar Area End -->
        </div>
    </div>
</section>
{% endblock %}